-- CREATE UNIQUE INDEX pk_${senses_senses.table} ON ${senses_senses.table}(${senses_senses.lu1id},${senses_senses.synset1id},${senses_senses.lu2id},${senses_senses.synset2id},${senses_senses.relationid});
CREATE INDEX k_${senses_senses.table}_${senses_senses.relationid} ON ${senses_senses.table}(${senses_senses.relationid});
CREATE INDEX k_${senses_senses.table}_${senses_senses.synset1id} ON ${senses_senses.table}(${senses_senses.synset1id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.synset1id}_${senses_senses.lu1id} ON ${senses_senses.table}(${senses_senses.synset1id}, ${senses_senses.lu1id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.synset1id}_${senses_senses.word1id} ON ${senses_senses.table}(${senses_senses.synset1id}, ${senses_senses.word1id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.synset2id} ON ${senses_senses.table}(${senses_senses.synset2id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.synset2id}_${senses_senses.lu2id} ON ${senses_senses.table}(${senses_senses.synset2id}, ${senses_senses.lu2id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.synset2id}_${senses_senses.word2id} ON ${senses_senses.table}(${senses_senses.synset2id}, ${senses_senses.word2id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.lu1id} ON ${senses_senses.table}(${senses_senses.lu1id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.lu2id} ON ${senses_senses.table}(${senses_senses.lu2id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.word1id} ON ${senses_senses.table}(${senses_senses.word1id});
CREATE INDEX k_${senses_senses.table}_${senses_senses.word2id} ON ${senses_senses.table}(${senses_senses.word2id});
