-- ALTER TABLE  `${senses_senses.table}` ADD CONSTRAINT `pk_${senses_senses.table}` PRIMARY KEY                                         (`${senses_senses.synset1id}`,`${senses_senses.lu1id}`,`${senses_senses.lu2id}`,`${senses_senses.synset2id}`,`${senses_senses.relationid}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.relationid}`                          (`${senses_senses.relationid}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.synset1id}`                           (`${senses_senses.synset1id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.lu1id}`                               (`${senses_senses.lu1id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.word1id}`                             (`${senses_senses.word1id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.synset2id}`                           (`${senses_senses.synset2id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.lu2id}`                               (`${senses_senses.lu2id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.word2id}`                             (`${senses_senses.word2id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.word1id}_${senses_senses.synset1id}`  (`${senses_senses.word1id}`,`${senses_senses.synset1id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.lu1id}_${senses_senses.synset1id}`    (`${senses_senses.lu1id}`,`${senses_senses.synset1id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.word2id}_${senses_senses.synset2id}`  (`${senses_senses.word2id}`,`${senses_senses.synset2id}`);
ALTER TABLE     `${senses_senses.table}` ADD KEY        `k_${senses_senses.table}_${senses_senses.lu2id}_${senses_senses.synset2id}`    (`${senses_senses.lu2id}`,`${senses_senses.synset2id}`);
